### ISSUE TITLE
Add Sentry reports (checklist WIP)

### ISSUE THREAD

**Issue by zavelevsky** [bancorprotocol/webapp-v3#548]
We need to start by only reporting things that indicate something is broken on our end.
If we report errors we don't care about - we will ignore Sentry. 
We should use Sentry in a way that an error means stop and investigate it now.

List, WIP, please add:

- [ ] report invalid or missing API data
- [ ] report bad requests
- [ ] report unhandled exceptions
